server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/private_cloud?useUnicode=true&characterEncoding=utf8"
    username: root
    password: 123456
    initialSize: 1
    minIdle: 1
    maxActive: 50

mybatis:
  type-aliases-package: com.merrony.privatecloud.model
  mapper-locations: classpath:mapping/*Mapper.xml

logging:
  level:
    com.merrony.privatecloud:
      mapper: debug
      service: debug
      controller: info
